<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta charset="UTF-8">
    <title>Главная страница</title>
</head>
<body>

    <h2>Главная страница</h2>

    <form action="/address" method="post">
        <div>
           name: <input type="text" name="name"/>
        </div>
        <div>
           page: <input type="text" name="page"/>
        </div>
        <div>
            <input type="submit" value="Найти">
        </div>
    </form>

</body>
</html>