<div class="c-menu">
    <div class="c-menu-l">
        <span><a href="/"><img src="/static/img/home.svg" height="30" alt="Главная"/></a></span>
        <span><a href="/services">Услуги</a></span>
        <span><a href="/masters">Мастера</a></span>
    </div>
    <div class="c-menu-r">
        <span><a href="/cabinet"><img src="/static/img/avatar_default.svg" height="30" alt="Кабинет"/></a></span>
    </div>
</div>