<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Work Wave</title>
</head>
<body>
<div class="site">
    <div class="header">
        <div class="logo">
            <img src="icon.jpg" alt="Иконка">
            <h1>Work Wave</h1>
        </div>
        <div class="menu">
            <a href="/client" class="link">Соискателям</a>
            <a href="/company" class="link">Работодателям</a>
            <a href="/client/createresume">
                <button>Создать резюме</button>
            </a>
            <a href="/client/login">
                <button>Войти</button>
            </a>
        </div>
    </div>

    <div class="main_section">
        <img src="image.jpg" alt="Картинка">
        <h2>Поможем найти работу каждому</h2>
    </div>
</div>
</body>
</html>