<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Главная страница</title>
    <style>
        .container-menu {
            display: flex;
            justify-content: flex-end;
        }
    </style>
</head>
<body>

    <div class="container-menu"><a href="${app_path!}/cabinet"><img src="${app_path!}/static/img/avatar_default.svg" height="30" alt="кабинет"/></a> </div>
    <h1>Товары</h1>

    <div>
        <img src="${app_path!}/static/img/spring-logo.svg" height="30" alt="spring">
    </div>




</body>
</html>